name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone https://github.com/${{ github.repository }}.git .
          
      - name: Setup Flutter
        run: |
          git clone https://github.com/flutter/flutter.git
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
          export PATH="$GITHUB_WORKSPACE/flutter/bin:$PATH"
          flutter channel stable
          flutter upgrade
          flutter doctor

      - name: Build
        run: |
          export PATH="$GITHUB_WORKSPACE/flutter/bin:$PATH"
          flutter pub get
          flutter build web --release --base-href "/${{ github.event.repository.name }}/"

      - name: Deploy
        run: |
          cd build/web
          git init
          git add -A
          git commit -m "Deploy to GitHub Pages"
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:gh-pages
